<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find dyret_description)/urdf/inertias.urdf.xacro" />

	<xacro:property name="mx64at_width" value="0.05" />
	<xacro:property name="mx64at_depth" value="0.0402" />
	<xacro:property name="mx64at_height" value="0.0611" />

	<xacro:property name="fr05h101_width" value="0.051" />
	<xacro:property name="fr05h101_depth" value="0.033" />
	<xacro:property name="fr05h101_height" value="0.0405" />
	<xacro:property name="fr05h101_offset" value="0.003" />

	<xacro:macro name="mx64at" params="name">
		<link name="${name}">
			<visual>
				<origin rpy="${pi/2} ${pi} ${pi}"
					xyz="${-mx64at_width/2 + 0.0049} ${-mx64at_depth/2 - 0.0049} ${mx64at_height}" />
				<geometry>
					<mesh filename="package://dyret_description/meshes/MX-64AT_AR.STL"
						scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>

			<collision>
				<origin rpy="0 ${pi} ${pi/2}"
					xyz="0 0 ${mx64at_height/2}" />
				<geometry>
					<box size="${mx64at_width} ${mx64at_depth} ${mx64at_height}" />
				</geometry>
			</collision>

			<inertial>
				<!-- Based on: references/RX-64_INERTIA.pdf -->
				<mass value="0.1295" />
				<origin rpy="${pi/2} 0 0"
					xyz="0 -0.004 ${mx64at_height/2}" />
				<inertia
					ixx="0.00005645784" ixy="0" ixz="0"
					iyy="0.000029325728" iyz="0"
					izz="0.000045111809" />
			</inertial>
		</link>
	</xacro:macro>

	<xacro:macro name="fr05h101" params="name">
		<link name="${name}">
			<visual>
				<origin rpy="${pi/2} ${pi} ${pi}"
					xyz="${-fr05h101_width/2} ${-fr05h101_depth/2} ${fr05h101_offset}" />
				<geometry>
					<mesh filename="package://dyret_description/meshes/FR05-H101.STL"
						scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>

			<collision>
				<origin rpy="0 ${pi} 0" xyz="0 0 ${-fr05h101_height/2 + fr05h101_offset}" />
				<geometry>
					<box size="${fr05h101_width} ${fr05h101_depth} ${fr05h101_height - fr05h101_offset}" />
				</geometry>
			</collision>

			<xacro:box_inertia_inv mass="0.016" width="${fr05h101_width}"
				length="${fr05h101_depth}" height="${fr05h101_height}"
				r="${pi/2}" />
		</link>
	</xacro:macro>

	<!-- Use the following macros when building models: -->
	<xacro:macro name="mx64at_fr05h101" params="name">
		<xacro:mx64at name="${name}_servo" />
		<xacro:fr05h101 name="${name}_bracket" />
		<joint name="${name}" type="revolute">
			<parent link="${name}_servo" />
			<child link="${name}_bracket" />
			<origin xyz="0 -0.0025 0.013" rpy="0 0 ${pi/2}" />
			<limit
				lower="-1.57" upper="1.57"
				effort="6.0" velocity="6.597" />
			<dynamics friction="0.1" damping="0.0952" />
		</joint>
		<gazebo reference="${name}">
			<implicitSpringDamper>1</implicitSpringDamper>
			<erp>0.1</erp>
			<stopKd value="100000000.0" />
			<stopKp value="100000000.0" />
			<fudgeFactor value="0.5" />
		</gazebo>
	</xacro:macro>
</robot>
